### ISSUE TITLE
Add flag to inDir() that stops the dir from being rimrafed

### ISSUE THREAD

**Issue by binduwavell** [yeoman/yeoman-test#13]
In order to test a sub-generator, we like to run our app generator and then run the sub-generator in the generated project. Currently we rely on a hack to stop the app generated project from being wiped out, it would be great if there was a clean supported way to do this with an alternative fluent function inExistingProjectDir() or with a flag to inDir()

**Comment by deimyts** [comment]
+1 to this. I think that the default behavior of cleaning the directory is more useful most of the time, but I've run into several cases where accurate testing would be easier if it could be turned off.

@binduwavell's example of running a sub-generator in a pre-existing project is a good one. 

Another use case I've run into is when adding integration tests for complicated build scripts. For the build scripts to be testable *without manually generating a project*, I need to download and install the npm and bower dependencies. To avoid doing this every time I run the build script tests, which is both slow and unnecessary, I download them *once* into another folder, and copy them into the test directory when the tests are run. This faster than re-dowloading them, but still slow. It could be completely avoided if we had more control over setting up our directories for testing.

I know that you can use a callback to `inDir` to copy files into your testing directory, but this is awkward, confusing to use, and can create overly complicated test setups. In addition, the cleaning behavior is unintuitive—I would expect `inDir` to specify a directory, nothing more, and leave the responsibility for making sure the directory is clean to the user.

There are enough ways to clean a directory using other modules, like `rimraf` or `fs-extra` that it may not even be necessary to have a dedicated cleanup helper method, but this is probably just a matter of preference.

**Suggestions**
---
Extract the cleaning functionality into its own helper function. Maybe `cleanDir()`? I prefer this approach, because it keeps responsibilities separate, and gives the user more far more control over when and how to clean the directory.

Split `inDir()` into `inDir()` and `inCleanDir()`. This still keeps responsibility for cleaning into the `inCleanDir` method, which I don't like, but there is something to be said for the simplicity. At least this way you could pick the one that was appropriate for the job, and the name would more accurately reflect what the function does.

Allow inDir() to accept options giving more fine-grained control over how the directory should be cleaned. This could be a boolean flag, or perhaps an array of paths or glob patterns that would allow you to exclude certain files or directories from being removed. `rimraf`, which is what does the actual cleaning, already accepts globbing patterns, so maybe you could just accept a pattern and pass it through when you call rimraf? To me, this option seems overly complex, and probably the most difficult to use or to document, but it might work.

**Comment by urosjarc** [comment]
[Pull request #20 ](https://github.com/yeoman/yeoman-test/pull/20)

**Comment by mischah** [comment]
Fixed width 3accbc64ea41791f7f1ff71e272efac2b5d7fccf 🎉
