### ISSUE TITLE
Feature request: Add ability to install npm dependencies

### ISSUE THREAD

**Issue by alallier** [yeoman/yeoman-test#25]
Feature request: Add ability to install npm dependencies after generator is done running.

**Comment by mischah** [comment]
Hej, 

no need to request that feature :blush:
Is already there: http://yeoman.io/authoring/dependencies.html

Cheers, Michael

**Comment by alallier** [comment]
The `install` run loop doesn't seem to when unit testing and using `helpers.run` anyway to make that happen?

**Comment by mischah** [comment]
Ah. Got it 😄 
Not sure if that makes sense though. Cause installing takes a while.

What is your use case?

**Comment by alallier** [comment]
Yes it could take awhile. But I'm testing that my generator configures a `package.json` correctly and that it can successfully install the dependencies. And then eventually start my application to see if it configured the application according to dynamic keys inside of the `package.json`.

Granted you could just use child_process, that is what I am doing now.

**Comment by mischah** [comment]
My opinion:
This is something that doesn’t need be a feature of this module. Because it goes beyond unit testing.

But your usecase is valid.
I also felt the need for checking the output of one of the generators I maintain.
This is how I handled it: https://github.com/micromata/generator-bootstrap-kickstart/blob/master/.travis.yml#L29-L56

Leaving that open for discussion.

**Comment by alallier** [comment]
I agree with you. Thanks for the example.

**Comment by SBoudrias** [comment]
@alallier you need to explicit pass `withOptions({skipInstall: false})`
