### ISSUE TITLE
[feature request] withEnd helper

### ISSUE THREAD

**Issue by mitchallen** [yeoman/yeoman-test#31]
My generator calls **npm test** at the end on the generated package:

```
 end() {
    this.spawnCommand('npm', ['test']);
  }
```
But this causes a problem when I run the generator tests themselves because it is also calling ```end()```. (The generated package calls webpack as part of a pretest build script causing the generator tests to blow up when they can't find a dependency). 

I'd like a way to tell the generator tests to ignore either ```end()``` or the spawn command.

Perhaps something like this:

```
  beforeAll(() => {
    return helpers.run(path.join(__dirname, '../generators/app'))
      .withPrompts({someAnswer: true})
      .withEnd( false )
  });
```

Or if there is another way to do this, please let me know.

Package:  https://github.com/mitchallen/generator-mitchallen-react-component

Thanks.

**Comment by SBoudrias** [comment]
I think you should add an option `--no-testing` to your generator. When it's passed, skip the testing.

Then you just need to pass the option in your unit tests.

I don't think we want to change the way we run generators in tests; your issue is quite an edge case. Given there's a workaround for you, I'll close this ticket.
